services:

  rtu:
    image: javiersande/sg-rtu:latest
    tty: true
    networks:
      transportNetwork:
        ipv4_address: 10.0.0.3

  scada:
    image: javiersande/sg-scada:latest
    tty: true
    networks:
      transportNetwork:
        ipv4_address: 10.0.0.4

  powermeter1:
    image: powermeter:latest
    environment:
      - PM_ID=1
      - PM_IP=10.0.1.1
      - PM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10001
      - SAFE_THRESHOLD=10000
    networks:
      transportNetwork:
        ipv4_address: 10.0.1.1

  circuitbreaker1:
    image: circuitbreaker:latest
    environment:
      - CB_ID=1
      - CB_IP=10.0.1.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=20001
      - AUTO_MODE=1
    networks:
      transportNetwork:
        ipv4_address: 10.0.1.2

  powermeter2:
    image: powermeter:latest
    environment:
      - PM_ID=2
      - PM_IP=10.0.2.1
      - PM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10002
      - SAFE_THRESHOLD=10000
    networks:
      transportNetwork:
        ipv4_address: 10.0.2.1

  circuitbreaker2:
    image: circuitbreaker:latest
    environment:
      - CB_ID=2
      - CB_IP=10.0.2.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=20002
      - AUTO_MODE=1
    networks:
      transportNetwork:
        ipv4_address: 10.0.2.2

  powermeter3:
    image: powermeter:latest
    environment:
      - PM_ID=3
      - PM_IP=10.0.3.1
      - PM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10003
      - SAFE_THRESHOLD=10000
    networks:
      transportNetwork:
        ipv4_address: 10.0.3.1

  circuitbreaker3:
    image: circuitbreaker:latest
    environment:
      - CB_ID=3
      - CB_IP=10.0.3.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=20003
      - AUTO_MODE=1
    networks:
      transportNetwork:
        ipv4_address: 10.0.3.2

  powermeter4:
    image: powermeter:latest
    environment:
      - PM_ID=4
      - PM_IP=10.0.4.1
      - PM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10004
      - SAFE_THRESHOLD=10000
    networks:
      transportNetwork:
        ipv4_address: 10.0.4.1

  circuitbreaker4:
    image: circuitbreaker:latest
    environment:
      - CB_ID=4
      - CB_IP=10.0.4.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=20004
      - AUTO_MODE=1
    networks:
      transportNetwork:
        ipv4_address: 10.0.4.2

networks:
  transportNetwork:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1